name: Docker Build CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest


    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Docker login
      run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} registry.cn-shenzhen.aliyuncs.com
    - name: Docker Build
      run: docker build -f DockerfileGithubAction -t registry.cn-shenzhen.aliyuncs.com/utek/gin-rtsp:master .  
    - name: Docker Push 
      run: docker push registry.cn-shenzhen.aliyuncs.com/utek/gin-rtsp:master  
